name: Nginx CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'

      - name: Grant execute permission for sh
        run: chmod +x build.sh

      - name: Build Nginx
        run: ./build.sh

      - name: Get Nginx dir
        uses: GenesisSam/get-simple-file-action@v1.0.5
        id: openFile
        with:
          file-name: NGINX_VERSION

      - name: Show dirs
        run: |
          ls -alh
          ls -alh objs
          objs/nginx -V

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-${{ steps.time.outputs.time }}
          path: ${{ steps.openFile.outputs.data }}/objs/nginx
          if-no-files-found: error
